name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
            node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint
